// example/next/app/page.tsx
"use client"

import { useCiph } from "./client-provider"
import { useState, useEffect } from "react"

interface Employee {
  id: number
  name: string
  role: string
  dept: string
  salary: number
  joined: string
  status: "active" | "inactive"
}

interface ApiResponse {
  received?: { message: string; timestamp: string }
  message?: string
  timestamp?: string
  error?: string
}

export default function Home() {
  const ciph = useCiph()
  const [response, setResponse] = useState<ApiResponse | null>(null)
  const [loading, setLoading] = useState(false)
  const [status, setStatus] = useState<"idle" | "success" | "error">("idle")
  const [employees, setEmployees] = useState<Employee[]>([])
  const [empLoading, setEmpLoading] = useState(false)
  const [empError, setEmpError] = useState<string | null>(null)

  const testCiph = async () => {
    setLoading(true)
    setResponse(null)
    setStatus("idle")
    try {
      const res = await ciph.post<ApiResponse>("/api/echo", {
        message: "Hello from Ciph + Next.js!",
        timestamp: new Date().toISOString(),
      })
      setResponse(res.data)
      setStatus("success")
    } catch (error) {
      setResponse({ error: (error as Error).message || "Request failed" })
      setStatus("error")
    }
    setLoading(false)
  }

  const fetchEmployees = async () => {
    setEmpLoading(true)
    setEmpError(null)
    try {
      const res = await ciph.get<{ data: Employee[]; total: number }>("/api/employees")
      setEmployees(res.data.data)
    } catch (error) {
      setEmpError((error as Error).message || "Failed to fetch employees")
    }
    setEmpLoading(false)
  }

  useEffect(() => {
    let cancelled = false
    const load = async () => {
      setEmpLoading(true)
      setEmpError(null)
      try {
        const res = await ciph.get<{ data: Employee[]; total: number }>("/api/employees")
        if (!cancelled) setEmployees(res.data.data)
      } catch (error) {
        if (!cancelled) setEmpError((error as Error).message || "Failed to fetch employees")
      }
      if (!cancelled) setEmpLoading(false)
    }
    load()
    return () => {
      cancelled = true
    }
  }, [ciph])

  return (
    <div className="min-h-screen bg-gradient-to-br from-slate-900 to-slate-800 text-white p-8">
      <div className="max-w-6xl mx-auto">
        <div className="mb-12">
          <h1 className="text-5xl font-bold mb-4">Ciph + Next.js</h1>
          <p className="text-xl text-slate-300">
            Transparent HTTP encryption with automatic request/response decryption
          </p>
        </div>

        {/* Echo Test Section */}
        <div className="bg-slate-800 rounded-lg p-8 border border-slate-700 mb-8">
          <h2 className="text-2xl font-bold mb-6">Test Encrypted Echo</h2>
          <p className="text-slate-300 mb-6">
            Click to send an encrypted POST request to the backend. Body is AES-256-GCM encrypted — plain
            text never touches the network.
          </p>
          <button
            onClick={testCiph}
            disabled={loading}
            className="bg-blue-600 hover:bg-blue-700 disabled:bg-slate-600 px-6 py-3 rounded-lg font-semibold transition mb-6"
          >
            {loading ? "Encrypting & sending…" : "Test Ciph → POST /api/echo"}
          </button>

          {response && (
            <div
              className={`p-6 rounded-lg border ${
                status === "error"
                  ? "bg-red-900/20 border-red-700 text-red-300"
                  : "bg-green-900/20 border-green-700 text-green-300"
              }`}
            >
              <p className="font-bold mb-3">
                {status === "error"
                  ? "❌ Error"
                  : "✅ Response received (decrypted by @ciph/react)"}
              </p>
              <pre className="text-sm overflow-x-auto">
                {JSON.stringify(response, null, 2)}
              </pre>
            </div>
          )}
        </div>

        {/* Employees Table Section */}
        <div className="bg-slate-800 rounded-lg p-8 border border-slate-700">
          <div className="flex justify-between items-center mb-6">
            <h2 className="text-2xl font-bold">
              Employees <span className="text-slate-400 text-lg font-normal">GET /api/employees (encrypted)</span>
            </h2>
            <button
              onClick={fetchEmployees}
              disabled={empLoading}
              className="bg-green-600 hover:bg-green-700 disabled:bg-slate-600 px-4 py-2 rounded font-semibold transition"
            >
              {empLoading ? "Loading…" : "Refresh"}
            </button>
          </div>

          {empError && <p className="text-red-400 mb-4">{empError}</p>}

          {!empLoading && employees.length > 0 && (
            <div className="overflow-x-auto border border-slate-700 rounded-lg">
              <table className="w-full text-sm">
                <thead className="bg-slate-700 border-b border-slate-700">
                  <tr>
                    <th className="px-4 py-3 text-left font-semibold">ID</th>
                    <th className="px-4 py-3 text-left font-semibold">Name</th>
                    <th className="px-4 py-3 text-left font-semibold">Role</th>
                    <th className="px-4 py-3 text-left font-semibold">Dept</th>
                    <th className="px-4 py-3 text-left font-semibold">Salary</th>
                    <th className="px-4 py-3 text-left font-semibold">Joined</th>
                    <th className="px-4 py-3 text-left font-semibold">Status</th>
                  </tr>
                </thead>
                <tbody>
                  {employees.map((emp, i) => (
                    <tr
                      key={emp.id}
                      className={`border-b border-slate-700 ${i % 2 === 0 ? "bg-slate-800" : "bg-slate-750"}`}
                    >
                      <td className="px-4 py-3 text-slate-400">{emp.id}</td>
                      <td className="px-4 py-3 font-semibold">{emp.name}</td>
                      <td className="px-4 py-3 text-slate-300">{emp.role}</td>
                      <td className="px-4 py-3 text-slate-300">{emp.dept}</td>
                      <td className="px-4 py-3 text-slate-300">${emp.salary.toLocaleString()}</td>
                      <td className="px-4 py-3 text-slate-400">{emp.joined}</td>
                      <td className="px-4 py-3">
                        <span
                          className={`px-3 py-1 rounded-full text-xs font-semibold ${
                            emp.status === "active"
                              ? "bg-green-900 text-green-200"
                              : "bg-slate-600 text-slate-300"
                          }`}
                        >
                          {emp.status}
                        </span>
                      </td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>
          )}

          {empLoading && (
            <div className="text-center text-slate-400 py-8">Loading encrypted data…</div>
          )}
        </div>

        {/* Info Box */}
        <div className="mt-8 bg-slate-800 rounded-lg p-6 border border-slate-700 text-sm text-slate-300">
          <h3 className="font-bold mb-3 text-white">🔐 How Ciph Works:</h3>
          <ul className="space-y-2 list-disc list-inside">
            <li>All requests/responses encrypted with AES-256-GCM</li>
            <li>Fingerprint validation ensures device-specific encryption</li>
            <li>Open DevTools Network tab to see ciphertext (not readable)</li>
            <li>No manual encrypt/decrypt in app code — fully transparent</li>
            <li>v1 symmetric mode using shared secret (CIPH_SECRET)</li>
          </ul>
        </div>
      </div>
    </div>
  )
}

// example/vue/src/App.vue
<script setup lang="ts">
import { ref, onMounted } from 'vue'
import { useCiph } from '@ciph/vue'
import vueLogo from './assets/vue.svg'
import viteLogo from './assets/vite.svg'
import heroImg from './assets/hero.png'

const ciph = useCiph()

// ─── Echo ─────────────────────────────────────────────────────────────────────

type ApiResponse = {
  received?: { message: string; timestamp: string }
  message?: string
  timestamp?: string
  error?: string
}

const echoResponse = ref<ApiResponse | null>(null)
const echoLoading = ref(false)
const echoStatus = ref<'idle' | 'success' | 'error'>('idle')

async function testCiph(): Promise<void> {
  echoLoading.value = true
  echoResponse.value = null
  echoStatus.value = 'idle'
  try {
    const res = await ciph.post<ApiResponse>('/api/echo', {
      message: 'Hello from Ciph v2 (ECDH)!',
      timestamp: new Date().toISOString(),
    })
    echoResponse.value = res.data
    echoStatus.value = 'success'
  } catch (err) {
    echoResponse.value = { error: (err as Error).message || 'Request failed' }
    echoStatus.value = 'error'
  }
  echoLoading.value = false
}

// ─── Employees ────────────────────────────────────────────────────────────────

type Employee = {
  id: number
  name: string
  role: string
  dept: string
  salary: number
  joined: string
  status: 'active' | 'inactive'
}

const employees = ref<Employee[]>([])
const empLoading = ref(false)
const empError = ref<string | null>(null)

async function fetchEmployees(): Promise<void> {
  empLoading.value = true
  empError.value = null
  try {
    const res = await ciph.get<{ data: Employee[]; total: number }>('/api/employees')
    employees.value = res.data.data
  } catch (err) {
    empError.value = (err as Error).message || 'Failed to fetch employees'
  }
  empLoading.value = false
}

onMounted(fetchEmployees)
</script>

<template>
  <section id="center">
    <div class="hero">
      <img :src="heroImg" class="base" width="170" height="179" alt="" />
      <img :src="vueLogo" class="framework" alt="Vue logo" />
      <img :src="viteLogo" class="vite" alt="Vite logo" />
    </div>

    <div style="text-align: center">
      <h1>Ciph Example</h1>
      <p style="color: var(--text-2); margin-bottom: 24px">
        Click the button to send an encrypted POST request to the backend.<br />
        Body is AES-256-GCM encrypted — plain text never touches the network.
      </p>
      <button class="counter" :disabled="echoLoading" @click="testCiph">
        {{ echoLoading ? 'Encrypting & sending…' : 'Test Ciph → POST /api/echo' }}
      </button>
    </div>

    <div
      v-if="echoResponse"
      :style="{
        width: '100%',
        maxWidth: '520px',
        padding: '20px 24px',
        background: echoStatus === 'error' ? '#fff1f2' : '#f0fdf4',
        border: `1px solid ${echoStatus === 'error' ? '#fecdd3' : '#bbf7d0'}`,
        borderRadius: '10px',
        textAlign: 'left',
      }"
    >
      <p
        :style="{
          margin: '0 0 12px',
          fontWeight: 600,
          fontSize: '14px',
          color: echoStatus === 'error' ? '#dc2626' : '#16a34a',
        }"
      >
        {{
          echoStatus === 'error'
            ? '❌ Error'
            : '✅ Response received (decrypted by @ciph/vue — ECDH v2)'
        }}
      </p>
      <pre style="margin: 0; fontSize: 13px; lineHeight: 1.6; overflowX: auto; color: #111827; background: transparent">{{
        JSON.stringify(echoResponse, null, 2)
      }}</pre>
    </div>

    <!-- Employees table -->
    <div style="width: 100%; max-width: 860px; margin-top: 32px">
      <div style="display: flex; justify-content: space-between; align-items: center; margin-bottom: 12px">
        <h2 style="margin: 0; font-size: 16px; font-weight: 600">
          Employees
          <span style="color: var(--text-2); font-weight: 400; font-size: 13px">
            GET /api/employees (encrypted)
          </span>
        </h2>
        <button
          :disabled="empLoading"
          style="padding: 5px 12px; font-size: 12px; cursor: pointer; border-radius: 6px; border: 1px solid #e5e7eb; background: #fff"
          @click="fetchEmployees"
        >
          {{ empLoading ? 'Loading…' : 'Refresh' }}
        </button>
      </div>

      <p v-if="empError" style="color: #dc2626; font-size: 13px; margin-bottom: 8px">{{ empError }}</p>

      <div
        v-if="!empLoading && employees.length > 0"
        style="border: 1px solid #e5e7eb; border-radius: 8px; overflow: hidden"
      >
        <table style="width: 100%; border-collapse: collapse; font-size: 13px">
          <thead>
            <tr style="background: #f9fafb">
              <th
                v-for="col in ['ID', 'Name', 'Role', 'Dept', 'Salary', 'Joined', 'Status']"
                :key="col"
                style="padding: 10px 14px; text-align: left; font-weight: 600; color: #374151; border-bottom: 1px solid #e5e7eb; white-space: nowrap"
              >{{ col }}</th>
            </tr>
          </thead>
          <tbody>
            <tr
              v-for="(emp, i) in employees"
              :key="emp.id"
              :style="{ background: i % 2 === 0 ? '#fff' : '#fafafa' }"
            >
              <td style="padding: 9px 14px; color: #6b7280">{{ emp.id }}</td>
              <td style="padding: 9px 14px; font-weight: 500; color: #111827">{{ emp.name }}</td>
              <td style="padding: 9px 14px; color: #374151">{{ emp.role }}</td>
              <td style="padding: 9px 14px; color: #374151">{{ emp.dept }}</td>
              <td style="padding: 9px 14px; color: #374151">${{ emp.salary.toLocaleString() }}</td>
              <td style="padding: 9px 14px; color: #6b7280">{{ emp.joined }}</td>
              <td style="padding: 9px 14px">
                <span
                  :style="{
                    padding: '2px 8px',
                    borderRadius: '12px',
                    fontSize: '11px',
                    fontWeight: 600,
                    background: emp.status === 'active' ? '#dcfce7' : '#f3f4f6',
                    color: emp.status === 'active' ? '#16a34a' : '#6b7280',
                  }"
                >{{ emp.status }}</span>
              </td>
            </tr>
          </tbody>
        </table>
      </div>

      <p
        v-if="empLoading"
        style="text-align: center; color: var(--text-2); font-size: 13px; padding: 20px 0"
      >
        Loading encrypted data…
      </p>
    </div>
  </section>

  <div class="ticks" />

  <section id="next-steps">
    <div id="docs">
      <svg class="icon" role="presentation" aria-hidden="true">
        <use href="/icons.svg#documentation-icon" />
      </svg>
      <h2>Debug</h2>
      <p>Use Ciph devtools to inspect encrypted traffic in plain text.</p>
      <ul>
        <li>
          <a href="http://localhost:4321" target="_blank" rel="noopener noreferrer">
            Backend Inspector (port 4321)
          </a>
        </li>
      </ul>
    </div>
  </section>
</template>
